spring.application.name=Internship-Tracker-API
#Port configuration
server.port=8080

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/internship_tracker
spring.datasource.username=postgres
spring.datasource.password=Postgres123
spring.jpa.hibernate.ddl-auto=update
#  //This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path =/internshiptracker